### ISSUE TITLE
[BUG] Can't compile. libgit2 not included on README

### ISSUE THREAD

**Issue by igoracmelo** [tulip-sudo/Kirigami64#11]
# Description
When I try to compile, I get this error:
```
/build/src/Kirigami64_autogen/EWIEGA46WW/../../../../src/backend.h:4:10: fatal error: git2.h: No such file or directory
    4 | #include <git2.h>
      |          ^~~~~~~~
compilation terminated.
```

# Steps to reproduce
Clone repository, install dependencies and try to `./compile`.

# Expected Outcome
Compiling properly

# Actual outcome
Error because I don't have libgit2 I guess.

# Screenshots
![image](https://user-images.githubusercontent.com/85039990/193666598-653538dc-873e-4b4c-8eee-38e8bb2a2a6a.png)

# System Information
 - OS: Kubuntu 20.04
 - Distro: Kubuntu 20.04
 - Desktop Environment and/or Window Manager: KDE
 - Kirigami64 Version: main (71eb0c19ea8c7c62ef4ab8fa0638d62091d4291b)

**Comment by igoracmelo** [comment]
I think the solution on Ubuntu and probably Debian based distro is to install `libgit2-dev` and `libboost-dev`.

**Comment by tulip-sudo** [comment]
Yeah, the solution is to just install the libgit2 packages.

**Comment by igoracmelo** [comment]
I still can't compile it... Now I'm having this error:
```
[  0%] Building CXX object src/CMakeFiles/Kirigami64.dir/main.cpp.o
/tmp/Kirigami64/src/main.cpp: In function ‘int main(int, char**)’:
/tmp/Kirigami64/src/main.cpp:59:2: error: ‘qmlRegisterSingletonInstance’ was not declared in this scope; did you mean ‘qmlRegisterSingletonType’?
```

**Comment by tulip-sudo** [comment]
From what I've gathered, it seems that your installatiion of the Qt Framework might not be entirely up to date (Ubuntu 20.04 has 5.12 but qmlRegisterSingletonInstance was added in 5.14)

**Comment by tulip-sudo** [comment]
Tested compiling on Ubuntu 22.04.1 LTS (within WSL) and I did not get this compilation error so I'd recommend upgrading to the newest Kubuntu LTS.
