### ISSUE TITLE
[BUG] unable to launch

### ISSUE THREAD

**Issue by Anti-Apple4life** [tulip-sudo/Kirigami64#8]
# Description
Description here:
I am unable to launch Kirigami64, and when I try to, I get a segmentation fault
# Steps to reproduce
Steps to reproduce the bug:
just build the program
# Expected Outcome
What should occur when running the program:
the program should output info for usage
# Actual outcome
What occurred when running the program:
it prints `[1]    93933 segmentation fault (core dumped)  ./Kirigami64`
# Screenshots
Outputs when running the program
```
➜  bin git:(main) ./Kirigami64
[1]    93933 segmentation fault (core dumped)  ./Kirigami64
```

# System Information
 - OS: Arch Linux
 - Distro: Arch Linux
 - Desktop Environment and/or Window Manager: KDE Plasma
 - Kirigami64 Version: commit cfe0b4781e367afb61b244a925736b89fc6750f5

# Additional notes
Additional notes here

**Comment by azreigh** [comment]
**Incredibly** late response but @Anti-Apple4life, can you see if the segmentation fault still occurs for you using the latest commit? If it works, I'll close this issue.

**Comment by Anti-Apple4life** [comment]
Building does not work anymore, I get the error "configuring incomplete, errors occurred!"

**Comment by azreigh** [comment]
Can you try recursively recloning?
`git clone --recurse-submodules https://www.github.com/azreigh/Kirigami64`

**Comment by tulip-sudo** [comment]
Alright, the repo no longer includes libgit2 as a submodule so is it possible for you to reclone normally (and install libgit2 seperately via pacman) and try recompiling?
